# Configuration for Case 1: Standard Bearing Fault Diagnosis

# File paths
name: "case1"
save_dir: "/home/lq/LQcode/2_project/PHMBench/PHMGA/save" # Add a general save directory
metadata_path: "/mnt/crucial/LQ/PHM-Vibench/metadata_6_11.xlsx"
h5_path: "/mnt/crucial/LQ/PHM-Vibench/cache.h5"
state_save_path: "/home/lq/LQcode/2_project/PHMBench/PHMGA/save/case1/case1_built_state.pkl"
report_path: "/home/lq/LQcode/2_project/PHMBench/PHMGA/save/case1/case1_final_report.md"

# Data selection
ref_ids:
  - 47050
  - 47044
  - 47047
  - 47053
  - 47056
test_ids:
  - 47051
  - 47045
  - 47048
  - 47054
  - 47057

builder:
  min_depth: 2
  max_depth: 5

# User instruction for the LLM
user_instruction: >
  Analyze the bearing signals for potential faults. The reference set contains signals
  for 5 different states (health, ball, cage, inner, outer). The test set also
  contains signals for the same 5 states. The goal is to correctly classify each
  test signal by comparing it to the reference set.
