# @package _global_
cases:
  selected: case1

name: case1
run_executor: true
train_backend: shallow
allow_test_labels_for_reporting: false

builder:
  min_depth: 4
  max_depth: 8
  max_iterations: 50
