"""State definitions for the PHM system."""

from __future__ import annotations

import operator
import uuid
from typing import Any, Dict, List, TypedDict, Annotated

from pydantic import BaseModel, Field

__all__ = [
    "SignalData",
    "ProcessedSignal",
    "ExtractedFeatures",
    "AnalysisInsight",
    "PHMState",
]


class SignalData(BaseModel):
    """Represents a batch of raw signals."""

    signal_id: str = Field(default_factory=lambda: f"sig_{uuid.uuid4().hex[:8]}")
    data: List[List[List[float]]]
    sampling_rate: int
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ProcessedSignal(BaseModel):
    """Result of a signal processing method."""

    processed_id: str = Field(default_factory=lambda: f"proc_{uuid.uuid4().hex[:8]}")
    source_signal_id: str
    method: str
    processed_data: Any


class ExtractedFeatures(BaseModel):
    """Features extracted from processed signal."""

    feature_set_id: str = Field(default_factory=lambda: f"feat_{uuid.uuid4().hex[:8]}")
    source_processed_id: str
    features: List[Dict[str, float]]


class AnalysisInsight(BaseModel):
    """An insight generated by analysis or reflection."""

    insight_id: str = Field(default_factory=lambda: f"ins_{uuid.uuid4().hex[:8]}")
    content: str
    severity_score: float = Field(ge=0.0, le=1.0)
    supporting_feature_ids: List[str]


class PHMState(TypedDict):
    """Central state object for the PHM system."""

    user_instruction: str
    reference_signal: SignalData
    test_signal: SignalData

    plan: Dict[str, Any]
    reflection_history: List[str]
    is_sufficient: bool
    iteration_count: int

    processed_signals: Annotated[List[ProcessedSignal], operator.add]
    extracted_features: Annotated[List[ExtractedFeatures], operator.add]

    analysis_results: List[AnalysisInsight]
    final_decision: str

    final_report: str
